extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/**/*.bril'
# benchmarks = '../examples/**/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.dce]
pipeline = [
    "bril2json",
    "python dce.py",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "python lvn.py",
    "brili -p {args}",
]
